# name: Run tests for house project
on:
  pull_request:
    branches:
      - "master"
# jobs:
#   run_unit_tests:
#     runs-on: macos-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3
#       - name: Flutter actions
#         uses: subosito/flutter-action@v2
#       - name: Get flutter packages
#         run: fluter pub get
